export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const DEMO_SCREEN = 'DEMO_SCREEN';
export const EVALUATE_SCREEN = 'EVALUATE_SCREEN';
export const RECENTS_SCREEN = 'RECENTS_SCREEN';
export const SET_VIDEO_DIR = 'SET_VIDEO_DIR';
export const SET_VIDEO_NAME = 'SET_VIDEO_NAME';
export const SET_EXTRACT_PATH = 'SET_EXTRACT_PATH';
export const SET_ACTIVE_STEPS = 'SET_ACTIVE_STEPS';

